### ISSUE TITLE
Example generated SBOM? (IDFGH-11001)

### ISSUE THREAD

**Issue by fpgax** [espressif/esp-idf-sbom#2]
Hi! Do you have an example SBOM file generated by this tool?

**Comment by fhrbata** [comment]
Hello @fpgax , 

here is a very simple SPDX SBOM for the 'hello_world` example [sbom.txt](https://github.com/espressif/esp-idf-sbom/files/12520153/sbom.txt). Note that usually it has `.spdx` extension, but GH is complaining about it during upload, so I changed it to `.txt`.

The information contained in the generated sbom and its size depends on options used for the generation. The uploaded example contains just very basic package info. The command, which was used to generate the sbom, is present in the comment at the top of the sbom file.

Thank you

**Comment by fpgax** [comment]
Thank you - much appreciated!
