### ISSUE TITLE
SBOM data for mbedtls @ esp-idf (IDFGH-11278)

### ISSUE THREAD

**Issue by fpgax** [espressif/esp-idf-sbom#4]
Hi!

For mbedtls you added this commit:
https://github.com/espressif/mbedtls/commit/bb6ae0d960d1e073de7d6552fcde9af1d127e6d6

to support the SBOM generation for the mbedtls library.

Now I'm wondering: Is this truly ARMs mbedtls or should it rather be viewed as an Espressif fork of mbedtls?

I can see a few commits on top that seem to originate from Espressif, so it's certainly slightly different than the pure ARM mbedtls version.

Now I was wondering if you have an opinion on this and how it's best handled in the SBOM data? Should a new CPE be registered or should it perhaps be expressed in some other field of the SBOM to clarify?

**Comment by mahavirj** [comment]
Yes, we do maintain few patches on top of the pristine mbedtls version. You may find them (few top commits) [here](https://github.com/espressif/mbedtls/commits/mbedtls-3.4.1-idf).

Just to note that some of these patches have been merged upstream and should already be part of the latest upstream release. Remaining ones allow us to support our hardware accelerator ports, they don't add any new feature or design level changes in the upstream code as such. 

Hence, I agree with @fhrbata of modifying the description field and continue to use with the existing CPE.

**Comment by fhrbata** [comment]
Note about additional features and patches from Espressif was added to the mbedtls sbom.yml description here 
https://github.com/espressif/mbedtls/commit/eda6f5b6d34c93d66e38b5d7b3ef8d1ddc6ca727. Implementing something like virtual packages mentioned above is still an option and we track it internally. As discussed the note should be hopefully enough for now, so I'm closing this.

@fpgax thank you very much for bringing this up!
